### ISSUE TITLE
Issues saving project settings and base rate drop down

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1437] opened 2019-10-24 10:43 UTC
- DAO's tokens are not being displayed in the list for Base Rate even though they exist in vault (when hourly)
- When switching to Fixed funding, and base rate has "select an item" there is an error, and cannot save the settings.

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/7a0d0415-cd6a-4d29-b934-406f677cfc30)

**Comment by ottodevs** [comment] 2019-10-24 21:24
I cannot reproduce the first part.
Maybe it depends on how you issue the tokens, I normally deposit tokens to the vault by using the Finance app, I think that is the correct way to do it.

![image](https://user-images.githubusercontent.com/5030059/67526553-52318000-f6b5-11e9-9061-14d453d09fd2.png)

**Comment by ottodevs** [comment] 2019-10-24 22:39
Let's keep this here for some more time, but for now I couldn't reproduce any of the 2 issues with latest `dev`
Waiting for fixed confirmation from @stellarmagnet to close it

**Comment by chadoh** [comment] 2019-11-05 15:24
From @philh:

> I'm having an error while trying to access my autark test org on rinkeby, I can't even restart the app without getting an error message, anyone out there with the same issue?
> hmm... I managed to restart everything by hitting the base URL (rinkeby.aragon.org) and choosing my org again, but then when accessing the Projects app...
> 
> ![something went wrong: u r.token is not defined](https://user-images.githubusercontent.com/221614/68220606-0b496180-ffb6-11e9-861b-9f3f744cccb9.png)
> 
> it might be related to the fact that i've been testing the use of a non-ETH token in my funding settings
> 
> I tried starting a new org with no special token... now, if I click on the base rate currency drop down list in the setting page, i see only ETH. I thought I could see another token earlier, and that I picked it, but now that I can't see it anymore I have doubts

**Comment by e18r** [comment] 2019-11-05 16:07
I was able to reproduce the part about the custom token not showing up in the base rate dropdown. Working on it now.

**Comment by e18r** [comment] 2019-11-05 16:59
Steps to reproduce on local environment:

1. Spin up a new DAO instance
2. Go to Projects -> Settings, set Funding Model to Hourly, check the Base Rate Dropdown
3. Only ETH appears in the dropdown - that's expected
4. Go to Tokens, copy the DAO token address
5. Go to Finance, transfer some DAO tokens to the DAO
6. Repeat step 2. The DAO token now appears in the dropdown - that's expected
7. Run `npm run mine 10000`, the following error should appear multiple times and the prompt shouldn't come back:

        mineBlock error:  { [Error: ESOCKETTIMEDOUT] message: 'ESOCKETTIMEDOUT', code: -32603 }
![Screenshot from 2019-11-05 11-57-34](https://user-images.githubusercontent.com/16065447/68228553-a7c63080-ffc3-11e9-9725-0b50b8e7b0bd.png)

8. Refresh the browser
9. Repeat step 2. The DAO token doesn't appear in the dropdown - quod erat demonstrandum.

**Closed** 2019-11-06 22:33 UTC
Labels: app: projects
