### ISSUE TITLE
Recurring Dividend 'action impossible' 

### ISSUE THREAD

**Issue by edlondon** [AutarkLabs/open-enterprise#1814] opened 2019-12-20 15:58 UTC
**Describe the bug**
Unable to vote on confirming the launch of a reward for 30 successive weeks of HMP 

https://etherscan.io/tx/0xbe104985fc928fb22a12d1b6f54466db64cd97b7284a6cd21fa165532d667b7d

**Mainnet or testnet?**
Mainet

**Organization**

Aloha.aragonid.eth

**To Reproduce**

1. Go to 'rewards'
2. Click on 'New Reward.'
3. Scroll down to 'Recurring Dividend'
4. See error once go to the voting and attempt to execute

**Expected behavior**

**Screenshots**

![IMG_0661](https://user-images.githubusercontent.com/10546852/71267004-7621e280-2341-11ea-9c3d-b6dfa72315c6.jpeg)

**Desktop (please complete the following information):**
 - OS and OS version: [e.g. Linux Mint 18.0]
 - Browser and browser version: [e.g. Firefox 64.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. Fairphone 2]
 - OS and OS version: [e.g. Android 8.0.0]
 - Browser and browser version: [e.g. Firefox 64.0.1]

**Additional context**

**Comment by topocount** [comment] 2019-12-20 16:07
Thanks for logging this Ed. could you share a screenshot of the configuration in the New Reward Panel for the multi-occurrence reward you submitted? It'll speed up our investigation of the issue here.

Thanks!

**Comment by topocount** [comment] 2019-12-20 16:15
Here's a screenshot of the radspec for the vote that's failing:
![image](https://user-images.githubusercontent.com/17910833/71268067-ab164100-2311-11ea-8ee4-6d7c27545b23.png)

**Comment by e18r** [comment] 2020-01-08 23:02
I'm closing this as I've been unable to reproduce this bug. Instead, I'm addressing the specific issue @edlondon had with him directly. It is being documented in ticket #1857.

**Closed by e18r** 2020-01-08 23:02 UTC
Labels: app: rewards, bug, maintenance
