### ISSUE TITLE
"No funds found" displayed, even though funds exist

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1552] opened 2019-11-07 07:13 UTC
1. Create a new DAO
2. Navigate to Organization and mint some test tokens
3. Navigate to Projects app. Connect a repo. Select an issue and "fund issue"

Will get a UI that says No funds found, even though I have funds in my finance app.

## Projects app
![image](https://user-images.githubusercontent.com/2584493/68367618-f02c3e00-00ea-11ea-982b-5a3b1bd0adf6.png)

## Finance app
![image](https://user-images.githubusercontent.com/2584493/68367658-0afeb280-00eb-11ea-900e-e8788ca11200.png)

**Comment by stellarmagnet** [comment] 2019-11-07 07:25
As soon as I deposit ETH, I no longer see this "No funds found". This means that it is checking the balance of the "default" currency (ETH), even though the funding model is fixed. 

Solution: When the funding model is fixed, we should omit checking the balance of the "default" currency. Instead, do the validation when the user is specifying the funding amount for the issue.

Otherwise, if there is a more intelligent way to do the validation here, let me know.

**Comment by jayalaves** [comment] 2019-11-07 17:06
@chadoh [See also here](https://www.youtube.com/watch?v=RqUKq8-qrF4&feature=youtu.be&t=3262), got the same error, but I don't know if it was for the same reasons. You can see the full footage on video.

**Comment by chadoh** [comment] 2019-11-07 17:45
@jayalaves yes, same root cause. Fixed in #1564

**Closed** 2019-11-07 22:50 UTC
Labels: app: projects
