### ISSUE TITLE
Any time I access the Settings tab, I see a broken avatar for a second

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1507] opened 2019-11-01 07:09 UTC
If logged in with Github, any time I access the Settings tab, my avatar is shown up as broken

![image](https://user-images.githubusercontent.com/2584493/68008333-ce8b0c80-fc3b-11e9-9da6-a160fc7a0383.png)

**Comment by PeterMPhillips** [comment] 2019-11-06 23:25
![Peek 2019-11-06 15-21](https://user-images.githubusercontent.com/19808076/68346566-4e383180-00a9-11ea-91eb-37057e46a153.gif)

Is it better if the text isn't displayed until the image is available? Or is this change in size too jarring upon loading?

**Comment by ottodevs** [comment] 2019-12-11 23:14
This was reviewed and merged in #1551 
It seems we are good closing it! (Feel free to re-open if needed, but comment the reason then!)
I tested locally and couldn't reproduce.

**Closed by ottodevs** 2019-12-11 23:14 UTC
Labels: app: projects
