### ISSUE TITLE
Projects filters: Some filters are not reflecting the correct number of items that fit for that filter

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/open-enterprise#961] opened 2019-06-07 15:00 UTC
I detected this issue here:

![image](https://user-images.githubusercontent.com/5030059/59113618-47ac5f00-893d-11e9-8ae9-3625538ecace.png)

It shows 5 funded issues, but only 2 are shown after applying the filter.

https://rinkeby.aragon.org/#/meshteam/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8

**Comment by Quazia** [comment] 2019-07-01 14:14
The first thing I would check here are whether this is affecting the display for issues filtered on something other than funding; I'm guessing this is only a problem with funding and the way we're filtering for that. Other potential issues could be related to the number of issues that have been loaded into state, but in that case I don't think there would be a discrepancy between the number in parens and the number of issues displayed.

**Comment by chadoh** [comment] 2019-07-01 17:50
I am unable to reproduce this error. @ottodevs do you know the steps that you went through in order to cause this bug? 

I am not able to sign into the Projects app using GitHub at the link provided, which prevents me from seeing this error there. I'm not sure having access would help me troubleshoot the bug or not, so if getting me permission takes a long time, no need to worry about it.

**Comment by stellarmagnet** [comment] 2019-07-03 21:20
I think this has to do with issues that were funded that later become closed

**Comment by stellarmagnet** [comment] 2019-08-30 09:20
Closing: this should be covered in #1113, once we provide support for displaying closed tickets

**Closed** 2019-08-30 09:20 UTC
Labels: app: projects, bug
