### ISSUE TITLE
Update syncing style in rewards

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1666] opened 2019-11-19 13:03 UTC
Right now Rewards looks like this when it's syncing and there's no data yet:

![aoeu](https://user-images.githubusercontent.com/2584493/69148743-44fd8a80-0ad5-11ea-99c2-cade6503a03e.png)

It should say it in the center instead. The "syncing data" thing should only be shown once there is data in the table and it's loading more

The 'Syncing' view should be displayed as follows when there's data in the process of syncing.

![Syncing](https://user-images.githubusercontent.com/28843778/70552747-3b1df300-1b7a-11ea-8157-41624a0993e1.png)

**Comment by javieralaves** [comment] 2019-12-10 17:40
@stellarmagnet @e18r I've updated the description for this issue with an updated view on how to style this sync view. The last bit to define is whether this sync applies to all the information displayed on the tab, or whether each section has a separate sync process (in the case of this tab, we have the metrics and table sections). I think the Finance app loads those separately. I'm personally inclined to have a global sync that accounts for all sections per tab; I don't think a separate sync per section is useful. Thoughts?

**Comment by e18r** [comment] 2019-12-11 15:31
Right now the empty card looks like this when it's syncing:
![Screenshot from 2019-12-11 10-25-17](https://user-images.githubusercontent.com/16065447/70634852-effaf300-1c00-11ea-8a8e-af0954b1c09d.png)
This looks as designed.

I guess the issue arises when there's data in one tab and not in the other, and so the empty card is shown inside one of the two tabs. I'm gonna try to reproduce that behavior.

**Comment by e18r** [comment] 2019-12-11 16:11
I'm having trouble reproducing this behavior:

* When no data has synced yet:
![Screenshot from 2019-12-11 10-53-36](https://user-images.githubusercontent.com/16065447/70638389-ca70e800-1c06-11ea-98da-e04be98ef8c9.png)

* When some data has synced already:
![Screenshot from 2019-12-11 11-06-25](https://user-images.githubusercontent.com/16065447/70638411-d65caa00-1c06-11ea-87b3-6254ca7be2af.png)

I'm gonna keep trying with a more code-oriented approach.

**Comment by e18r** [comment] 2019-12-11 16:41
Looking at the code, the described behavior seems impossible:
![Screenshot from 2019-12-11 11-32-33](https://user-images.githubusercontent.com/16065447/70640544-18d3b600-1c0a-11ea-8cdd-2000af1b927b.png)
The `SyncIndicator` element at the bottom of this code block is the small "Syncing data..." box from the screenshots. Note that it can't appear at the same time as the Empty card. This behavior is consistent with what I've been observing trying to reproduce on the UI.

@stellarmagnet @javieralaves Please make sure that this issue persists in the most up-to-date version of Rewards, and if so, please provide a step-by-step on how to reproduce. Moving to Review for now.

**Comment by javieralaves** [comment] 2019-12-16 07:33
Closing this for now until we revisit this pattern in testing and compare/contrast with other apps.

**Closed by javieralaves** 2019-12-16 07:33 UTC
Labels: app: rewards, mainnet
